name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: DesigniteJava Action
        uses: DesigniteTools/DJAction@v2.0
        with:
          PAT: ${{ secrets.PAT }}
      - name: Designite Incremental Code Quality Analysis
        uses: DesigniteTools/designite-incremental-analysis@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          designite-output-old: designite-output-${{ github.event.before }}
          designite-output-new: designite-output-${{ github.sha }}
          repo-name: ${{ github.repository }}
          tool-name: 'dj'